// AUTO-GENERATED by scripts/gen-route-titles (do not edit by hand).
// Maps a shared route key -> locale -> that page's <title>, used to give the
// footer language-switch links a title attr in the *target* language (SEO).

export const ROUTE_TITLES: Record<string, Record<string, string>> = {
  "/": {
    "ru": "Цифровое меню, кухонный дисплей и брони — IQ Rest",
    "en": "Digital Menu, Kitchen Display and Reservations — IQ Rest",
    "es": "Menú digital, pantalla de cocina y reservas — IQ Rest",
    "fr": "Menu digital, écran de cuisine et réservations — IQ Rest",
    "it": "Menù digitale, display cucina e prenotazioni — IQ Rest",
    "pt": "Ementa digital, ecrã de cozinha e reservas — IQ Rest"
  },
  "/digital-menu": {
    "ru": "Цифровое меню для ресторана | IQ Rest",
    "en": "Digital Menu for Restaurants | IQ Rest",
    "es": "Menú digital para restaurantes | IQ Rest",
    "fr": "Menu digital pour restaurant | IQ Rest",
    "it": "Menù digitale per ristoranti | IQ Rest",
    "pt": "Ementa digital para restaurante | IQ Rest"
  },
  "/order-taking": {
    "ru": "Приём заказов в ресторане — Гость и официант | IQ Rest",
    "en": "Restaurant Order Taking — Guest and Waiter | IQ Rest",
    "es": "Toma de comandas en el restaurante — comensal y camarero | IQ Rest",
    "fr": "Prise de commandes au restaurant — Client et serveur | IQ Rest",
    "it": "Ricezione degli ordini al ristorante — Ospite e cameriere | IQ Rest",
    "pt": "Receção de pedidos no restaurante — Cliente e empregado | IQ Rest"
  },
  "/bookings": {
    "ru": "Бронирование столов 24/7 для ресторана | IQ Rest",
    "en": "24/7 Table Reservations for Restaurants | IQ Rest",
    "es": "Reserva de mesas 24/7 para restaurantes | IQ Rest",
    "fr": "Réservation de tables 24h/24 pour restaurant | IQ Rest",
    "it": "Prenotazione dei tavoli 24/7 per ristoranti | IQ Rest",
    "pt": "Reserva de mesas 24/7 para restaurante | IQ Rest"
  },
  "/kitchen-display": {
    "ru": "Кухонный дисплей (KDS) для ресторана — Заказы на экран повара | IQ Rest",
    "en": "Kitchen Display System (KDS) for Restaurants — Orders on the Cook's Screen | IQ Rest",
    "es": "Pantalla de cocina (KDS) para restaurantes — Pedidos en la pantalla del cocinero | IQ Rest",
    "fr": "Écran de cuisine (KDS) pour restaurant — Les commandes sur l'écran du cuisinier | IQ Rest",
    "it": "Display cucina (KDS) per ristoranti — Ordini sullo schermo del cuoco | IQ Rest",
    "pt": "Ecrã de cozinha (KDS) para restaurante — Pedidos no ecrã do cozinheiro | IQ Rest"
  },
  "/menu-qr-code": {
    "ru": "QR-меню для ресторанов | IQ Rest",
    "en": "QR Menu for Restaurants | IQ Rest",
    "es": "Menú QR para restaurantes | IQ Rest",
    "fr": "Menu QR pour restaurants | IQ Rest",
    "it": "Menù QR per ristoranti | IQ Rest",
    "pt": "Ementa QR para restaurantes | IQ Rest"
  },
  "/pricing": {
    "ru": "Цены — конструктор тарифа для ресторана от 9.90 €/мес | IQ Rest",
    "en": "Pricing — Build Your Restaurant Plan from 9.90 €/mo | IQ Rest",
    "es": "Precios — configure la tarifa de su restaurante desde 9.90 €/mes | IQ Rest",
    "fr": "Tarifs — composez votre formule restaurant dès 9.90 €/mois | IQ Rest",
    "it": "Prezzi — configuratore del piano per ristoranti da 9.90 €/mese | IQ Rest",
    "pt": "Preços — plano modular para restaurante desde 9.90 €/mês | IQ Rest"
  },
  "/about": {
    "ru": "О компании IQ Rest — кто мы, контакты и реквизиты",
    "en": "About IQ Rest — Who We Are, Contacts and Legal Details",
    "es": "Sobre IQ Rest: quiénes somos, contacto y datos legales",
    "fr": "À propos d'IQ Rest — qui nous sommes, contacts et mentions légales",
    "it": "Chi siamo — IQ Rest: l'azienda, i contatti e i dati legali",
    "pt": "Sobre a IQ Rest — quem somos, contactos e dados legais"
  },
  "/help": {
    "ru": "Как пользоваться IQ Rest — пошаговая инструкция",
    "en": "How to use IQ Rest — step-by-step guide",
    "es": "Cómo usar IQ Rest — guía paso a paso",
    "fr": "Comment utiliser IQ Rest — guide pas à pas",
    "it": "Come usare IQ Rest — guida passo passo",
    "pt": "Como usar o IQ Rest — guia passo a passo"
  }
};

export function titleFor(routeKey: string | undefined, locale: string): string | undefined {
  if (!routeKey) return undefined;
  return ROUTE_TITLES[routeKey]?.[locale];
}
