// Payment-failed / dunning reminder — admin-triggered after a charge fails.
// Tells the owner to update their card and retry, warns the restaurant is
// switched off in 3 days (matches PAST_DUE_GRACE_DAYS in common/entitlements),
// and points them at support. Name-less by design (many owners never set a
// restaurant title). No price in copy — the CTA button (label {cta}, URL
// injected by MailService) sends them to the billing page.

interface T {
  subject: string;
  greeting: string;
  body: string;
  cta: string;
  help: string;
  closing: string;
  signature: string;
}

export const PAYMENT_FAILED: Record<string, T> = {
  ar: {
    subject: "لم تتم عملية الدفع — يرجى تحديث بطاقتك",
    greeting: "مرحبًا،",
    body: "لم نتمكن من إتمام آخر دفعة لك في IQ Rest. يرجى تحديث بيانات بطاقتك وإعادة محاولة الدفع للحفاظ على عمل مطعمك. إذا لم تتم عملية الدفع، فسيتم إيقاف مطعمك خلال 3 أيام.",
    cta: "تحديث الدفع",
    help: "إذا واجهت أي مشكلة، يمكنك دائمًا التواصل مع فريق الدعم لدينا — فقط رد على هذا البريد.",
    closing: "شكرًا لاستخدامك IQ Rest.",
    signature: "مع أطيب التحيات،<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  bg: {
    subject: "Плащането не мина — обнови картата си",
    greeting: "Здравей,",
    body: "Не успяхме да обработим последното ти плащане в IQ Rest. Моля, обнови данните на картата си и опитай плащането отново, за да продължи ресторантът ти да работи. Ако плащането не мине, ресторантът ти ще бъде изключен след 3 дни.",
    cta: "Обнови плащането",
    help: "Ако имаш някакви проблеми, винаги можеш да пишеш на нашата поддръжка — просто отговори на този имейл.",
    closing: "Благодаря, че използваш IQ Rest.",
    signature: "С уважение,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  ca: {
    subject: "El pagament ha fallat — actualitza la teva targeta",
    greeting: "Hola,",
    body: "No hem pogut processar el teu últim pagament d'IQ Rest. Actualitza les dades de la teva targeta i torna a provar el pagament per mantenir el teu restaurant en funcionament. Si el pagament no es completa, el teu restaurant es desactivarà d'aquí a 3 dies.",
    cta: "Actualitza el pagament",
    help: "Si tens cap problema, sempre pots escriure al nostre suport — només respon a aquest correu.",
    closing: "Gràcies per fer servir IQ Rest.",
    signature: "Salutacions,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  cs: {
    subject: "Platba se nezdařila — aktualizujte svou kartu",
    greeting: "Dobrý den,",
    body: "Nepodařilo se nám zpracovat vaši poslední platbu v IQ Rest. Aktualizujte prosím údaje o kartě a zkuste platbu znovu, aby vaše restaurace mohla dál fungovat. Pokud platba neproběhne, vaše restaurace bude za 3 dny deaktivována.",
    cta: "Aktualizovat platbu",
    help: "Pokud máte jakékoli potíže, můžete se vždy obrátit na naši podporu — stačí odpovědět na tento e-mail.",
    closing: "Děkuji, že používáte IQ Rest.",
    signature: "S pozdravem,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  da: {
    subject: "Betalingen mislykkedes — opdater dit kort",
    greeting: "Hej,",
    body: "Vi kunne ikke gennemføre din seneste IQ Rest-betaling. Opdater venligst dine kortoplysninger og prøv betalingen igen, så din restaurant kan fortsætte. Hvis betalingen ikke gennemføres, bliver din restaurant lukket ned om 3 dage.",
    cta: "Opdater betaling",
    help: "Hvis du har problemer, kan du altid kontakte vores support — svar bare på denne e-mail.",
    closing: "Tak fordi du bruger IQ Rest.",
    signature: "Venlig hilsen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  de: {
    subject: "Zahlung fehlgeschlagen — aktualisiere deine Karte",
    greeting: "Hallo,",
    body: "Wir konnten deine letzte IQ Rest-Zahlung nicht verarbeiten. Bitte aktualisiere deine Kartendaten und wiederhole die Zahlung, damit dein Restaurant weiterläuft. Wenn die Zahlung nicht durchgeht, wird dein Restaurant in 3 Tagen deaktiviert.",
    cta: "Zahlung aktualisieren",
    help: "Falls du Probleme hast, kannst du dich jederzeit an unseren Support wenden — antworte einfach auf diese E-Mail.",
    closing: "Danke, dass du IQ Rest nutzt.",
    signature: "Beste Grüße,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  el: {
    subject: "Η πληρωμή απέτυχε — ενημέρωσε την κάρτα σου",
    greeting: "Γεια σου,",
    body: "Δεν μπορέσαμε να επεξεργαστούμε την τελευταία σου πληρωμή στο IQ Rest. Ενημέρωσε τα στοιχεία της κάρτας σου και δοκίμασε ξανά την πληρωμή για να συνεχίσει να λειτουργεί το εστιατόριό σου. Αν η πληρωμή δεν ολοκληρωθεί, το εστιατόριό σου θα απενεργοποιηθεί σε 3 ημέρες.",
    cta: "Ενημέρωση πληρωμής",
    help: "Αν αντιμετωπίζεις οποιοδήποτε πρόβλημα, μπορείς πάντα να επικοινωνήσεις με την υποστήριξή μας — απλώς απάντησε σε αυτό το email.",
    closing: "Ευχαριστώ που χρησιμοποιείς το IQ Rest.",
    signature: "Με εκτίμηση,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  en: {
    subject: "Payment failed — update your card to keep your restaurant online",
    greeting: "Hi there,",
    body: "We couldn't process your latest IQ Rest payment. Please update your card details and retry the payment to keep your restaurant running. If the payment doesn't go through, your restaurant will be switched off in 3 days.",
    cta: "Update payment",
    help: "If you're having any trouble, you can always reach our support — just reply to this email.",
    closing: "Thanks for using IQ Rest.",
    signature: "Best regards,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  es: {
    subject: "El pago ha fallado — actualiza tu tarjeta",
    greeting: "Hola,",
    body: "No pudimos procesar tu último pago de IQ Rest. Actualiza los datos de tu tarjeta y vuelve a intentar el pago para mantener tu restaurante en funcionamiento. Si el pago no se completa, tu restaurante se desactivará en 3 días.",
    cta: "Actualizar pago",
    help: "Si tienes algún problema, siempre puedes escribir a nuestro soporte — solo responde a este correo.",
    closing: "Gracias por usar IQ Rest.",
    signature: "Saludos,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  et: {
    subject: "Makse ebaõnnestus — uuenda oma kaarti",
    greeting: "Tere,",
    body: "Me ei saanud sinu viimast IQ Resti makset töödelda. Palun uuenda oma kaardiandmeid ja proovi makset uuesti, et su restoran töötaks edasi. Kui makse ei õnnestu, lülitatakse su restoran 3 päeva pärast välja.",
    cta: "Uuenda makse",
    help: "Kui sul on mingeid probleeme, võid alati meie toega ühendust võtta — lihtsalt vasta sellele e-kirjale.",
    closing: "Aitäh, et kasutad IQ Resti.",
    signature: "Lugupidamisega,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fa: {
    subject: "پرداخت ناموفق بود — کارت خود را به‌روزرسانی کنید",
    greeting: "سلام،",
    body: "ما نتوانستیم آخرین پرداخت شما در IQ Rest را پردازش کنیم. لطفاً اطلاعات کارت خود را به‌روزرسانی کنید و پرداخت را دوباره امتحان کنید تا رستوران شما فعال بماند. اگر پرداخت انجام نشود، رستوران شما تا ۳ روز دیگر غیرفعال خواهد شد.",
    cta: "به‌روزرسانی پرداخت",
    help: "اگر با مشکلی روبه‌رو شدید، همیشه می‌توانید با پشتیبانی ما تماس بگیرید — کافی است به این ایمیل پاسخ دهید.",
    closing: "ممنون که از IQ Rest استفاده می‌کنید.",
    signature: "با احترام،<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fi: {
    subject: "Maksu epäonnistui — päivitä korttisi",
    greeting: "Hei,",
    body: "Emme voineet käsitellä viimeisintä IQ Rest -maksuasi. Päivitä korttitietosi ja yritä maksua uudelleen, jotta ravintolasi pysyy toiminnassa. Jos maksu ei mene läpi, ravintolasi suljetaan 3 päivän kuluttua.",
    cta: "Päivitä maksu",
    help: "Jos sinulla on ongelmia, voit aina ottaa yhteyttä tukeemme — vastaa vain tähän sähköpostiin.",
    closing: "Kiitos, että käytät IQ Restiä.",
    signature: "Ystävällisin terveisin,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fr: {
    subject: "Le paiement a échoué — mettez à jour votre carte",
    greeting: "Bonjour,",
    body: "Nous n'avons pas pu traiter votre dernier paiement IQ Rest. Merci de mettre à jour les informations de votre carte et de réessayer le paiement afin de garder votre restaurant actif. Si le paiement n'aboutit pas, votre restaurant sera désactivé dans 3 jours.",
    cta: "Mettre à jour le paiement",
    help: "Si vous rencontrez le moindre problème, vous pouvez toujours contacter notre support — répondez simplement à cet e-mail.",
    closing: "Merci d'utiliser IQ Rest.",
    signature: "Cordialement,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ga: {
    subject: "Theip ar an íocaíocht — nuashonraigh do chárta",
    greeting: "Dia duit,",
    body: "Ní rabhamar in ann d'íocaíocht IQ Rest is déanaí a phróiseáil. Nuashonraigh sonraí do chárta agus bain triail eile as an íocaíocht chun do bhialann a choinneáil ag rith. Mura n-éiríonn leis an íocaíocht, díchumasófar do bhialann i gceann 3 lá.",
    cta: "Nuashonraigh an íocaíocht",
    help: "Má bhíonn aon fhadhb agat, is féidir leat teagmháil a dhéanamh lenár dtacaíocht i gcónaí — freagair an ríomhphost seo.",
    closing: "Go raibh maith agat as IQ Rest a úsáid.",
    signature: "Le meas,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  hr: {
    subject: "Plaćanje nije uspjelo — ažuriraj svoju karticu",
    greeting: "Pozdrav,",
    body: "Nismo mogli obraditi tvoje posljednje plaćanje u IQ Restu. Molimo ažuriraj podatke o kartici i ponovno pokušaj plaćanje kako bi tvoj restoran nastavio raditi. Ako plaćanje ne uspije, tvoj će restoran biti isključen za 3 dana.",
    cta: "Ažuriraj plaćanje",
    help: "Ako imaš bilo kakvih problema, uvijek se možeš obratiti našoj podršci — samo odgovori na ovaj email.",
    closing: "Hvala što koristiš IQ Rest.",
    signature: "Pozdrav,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  hu: {
    subject: "A fizetés sikertelen — frissítsd a kártyádat",
    greeting: "Szia,",
    body: "Nem tudtuk feldolgozni a legutóbbi IQ Rest fizetésedet. Kérjük, frissítsd a kártyaadataidat, és próbáld újra a fizetést, hogy az éttermed tovább működhessen. Ha a fizetés nem sikerül, az éttermedet 3 nap múlva kikapcsoljuk.",
    cta: "Fizetés frissítése",
    help: "Ha bármilyen problémád van, mindig fordulhatsz az ügyfélszolgálatunkhoz — csak válaszolj erre az e-mailre.",
    closing: "Köszönjük, hogy az IQ Restet használod.",
    signature: "Üdvözlettel,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  is: {
    subject: "Greiðsla mistókst — uppfærðu kortið þitt",
    greeting: "Halló,",
    body: "Við gátum ekki unnið úr síðustu IQ Rest-greiðslunni þinni. Vinsamlegast uppfærðu kortaupplýsingarnar þínar og reyndu greiðsluna aftur til að halda veitingastaðnum þínum í gangi. Ef greiðslan gengur ekki í gegn verður veitingastaðurinn þinn tekinn úr sambandi eftir 3 daga.",
    cta: "Uppfæra greiðslu",
    help: "Ef þú lendir í einhverjum vandræðum geturðu alltaf haft samband við þjónustuna okkar — svaraðu bara þessum tölvupósti.",
    closing: "Takk fyrir að nota IQ Rest.",
    signature: "Bestu kveðjur,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  it: {
    subject: "Pagamento non riuscito — aggiorna la tua carta",
    greeting: "Ciao,",
    body: "Non siamo riusciti a elaborare il tuo ultimo pagamento IQ Rest. Aggiorna i dati della tua carta e riprova il pagamento per mantenere attivo il tuo ristorante. Se il pagamento non va a buon fine, il tuo ristorante verrà disattivato tra 3 giorni.",
    cta: "Aggiorna pagamento",
    help: "Se hai qualche problema, puoi sempre contattare il nostro supporto — ti basta rispondere a questa email.",
    closing: "Grazie per aver scelto IQ Rest.",
    signature: "Cordiali saluti,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ja: {
    subject: "お支払いが完了しませんでした — カード情報を更新してください",
    greeting: "こんにちは。",
    body: "IQ Rest の直近のお支払いを処理できませんでした。レストランの稼働を継続するため、カード情報を更新して再度お支払いをお試しください。お支払いが完了しない場合、3日後にレストランは停止されます。",
    cta: "支払いを更新",
    help: "何かお困りのことがあれば、いつでもサポートにご連絡いただけます。このメールに返信してください。",
    closing: "IQ Rest をご利用いただきありがとうございます。",
    signature: "よろしくお願いいたします。<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ko: {
    subject: "결제에 실패했습니다 — 카드 정보를 업데이트하세요",
    greeting: "안녕하세요,",
    body: "최근 IQ Rest 결제를 처리하지 못했습니다. 레스토랑을 계속 운영하려면 카드 정보를 업데이트하고 결제를 다시 시도해 주세요. 결제가 완료되지 않으면 3일 후에 레스토랑이 중지됩니다.",
    cta: "결제 업데이트",
    help: "문제가 있으시면 언제든지 저희 지원팀에 문의하실 수 있습니다 — 이 이메일에 회신해 주세요.",
    closing: "IQ Rest를 이용해 주셔서 감사합니다.",
    signature: "감사합니다.<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  lt: {
    subject: "Mokėjimas nepavyko — atnaujinkite savo kortelę",
    greeting: "Sveiki,",
    body: "Nepavyko apdoroti paskutinio jūsų IQ Rest mokėjimo. Atnaujinkite kortelės duomenis ir pakartokite mokėjimą, kad jūsų restoranas ir toliau veiktų. Jei mokėjimas nepavyks, jūsų restoranas bus išjungtas po 3 dienų.",
    cta: "Atnaujinti mokėjimą",
    help: "Jei kyla bet kokių problemų, visada galite kreiptis į mūsų pagalbos komandą — tiesiog atsakykite į šį laišką.",
    closing: "Ačiū, kad naudojatės IQ Rest.",
    signature: "Pagarbiai,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  lv: {
    subject: "Maksājums neizdevās — atjauniniet savu karti",
    greeting: "Sveiki,",
    body: "Mēs nevarējām apstrādāt jūsu pēdējo IQ Rest maksājumu. Lūdzu, atjauniniet savas kartes datus un mēģiniet maksājumu vēlreiz, lai jūsu restorāns turpinātu darboties. Ja maksājums neizdosies, jūsu restorāns tiks atslēgts pēc 3 dienām.",
    cta: "Atjaunināt maksājumu",
    help: "Ja jums ir kādas problēmas, jūs vienmēr varat sazināties ar mūsu atbalsta komandu — vienkārši atbildiet uz šo e-pastu.",
    closing: "Paldies, ka izmantojat IQ Rest.",
    signature: "Ar cieņu,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  nl: {
    subject: "Betaling mislukt — werk je kaart bij",
    greeting: "Hallo,",
    body: "We konden je laatste IQ Rest-betaling niet verwerken. Werk je kaartgegevens bij en probeer de betaling opnieuw om je restaurant actief te houden. Als de betaling niet lukt, wordt je restaurant over 3 dagen uitgeschakeld.",
    cta: "Betaling bijwerken",
    help: "Als je problemen hebt, kun je altijd contact opnemen met onze support — beantwoord gewoon deze e-mail.",
    closing: "Bedankt dat je IQ Rest gebruikt.",
    signature: "Met vriendelijke groet,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  no: {
    subject: "Betalingen mislyktes — oppdater kortet ditt",
    greeting: "Hei,",
    body: "Vi kunne ikke behandle din siste IQ Rest-betaling. Vennligst oppdater kortopplysningene dine og prøv betalingen på nytt for å holde restauranten din i gang. Hvis betalingen ikke går gjennom, blir restauranten din slått av om 3 dager.",
    cta: "Oppdater betaling",
    help: "Hvis du har problemer, kan du alltid kontakte support — bare svar på denne e-posten.",
    closing: "Takk for at du bruker IQ Rest.",
    signature: "Vennlig hilsen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  pl: {
    subject: "Płatność nie powiodła się — zaktualizuj kartę",
    greeting: "Cześć,",
    body: "Nie mogliśmy przetworzyć Twojej ostatniej płatności w IQ Rest. Zaktualizuj dane karty i ponów płatność, aby Twoja restauracja mogła dalej działać. Jeśli płatność się nie powiedzie, Twoja restauracja zostanie wyłączona za 3 dni.",
    cta: "Zaktualizuj płatność",
    help: "Jeśli masz jakiekolwiek problemy, zawsze możesz napisać do naszego wsparcia — po prostu odpowiedz na tę wiadomość.",
    closing: "Dziękujemy, że korzystasz z IQ Rest.",
    signature: "Pozdrawiam,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  pt: {
    subject: "O pagamento falhou — atualiza o teu cartão",
    greeting: "Olá,",
    body: "Não conseguimos processar o teu último pagamento no IQ Rest. Atualiza os dados do teu cartão e tenta novamente o pagamento para manter o teu restaurante em funcionamento. Se o pagamento não for concluído, o teu restaurante será desativado dentro de 3 dias.",
    cta: "Atualizar pagamento",
    help: "Se tiveres algum problema, podes sempre contactar o nosso suporte — basta responder a este email.",
    closing: "Obrigado por usares o IQ Rest.",
    signature: "Cumprimentos,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ro: {
    subject: "Plata a eșuat — actualizează-ți cardul",
    greeting: "Salut,",
    body: "Nu am putut procesa ultima ta plată IQ Rest. Te rugăm să actualizezi datele cardului și să reîncerci plata pentru ca restaurantul tău să funcționeze în continuare. Dacă plata nu reușește, restaurantul tău va fi dezactivat în 3 zile.",
    cta: "Actualizează plata",
    help: "Dacă întâmpini orice problemă, poți contacta oricând echipa noastră de suport — răspunde la acest e-mail.",
    closing: "Mulțumim că folosești IQ Rest.",
    signature: "Cu stimă,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ru: {
    subject: "Оплата не прошла — обновите данные карты",
    greeting: "Здравствуйте,",
    body: "Нам не удалось провести ваш последний платёж в IQ Rest. Пожалуйста, обновите данные карты и повторите платёж, чтобы ваш ресторан продолжал работать. Если платёж не пройдёт, ваш ресторан будет отключён через 3 дня.",
    cta: "Обновить оплату",
    help: "Если возникнут какие-либо проблемы, вы всегда можете написать в нашу поддержку — просто ответьте на это письмо.",
    closing: "Спасибо, что пользуетесь IQ Rest.",
    signature: "С уважением,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  sk: {
    subject: "Platba zlyhala — aktualizujte svoju kartu",
    greeting: "Dobrý deň,",
    body: "Nepodarilo sa nám spracovať vašu poslednú platbu v IQ Rest. Aktualizujte prosím údaje o karte a skúste platbu znova, aby vaša reštaurácia mohla ďalej fungovať. Ak platba neprebehne, vaša reštaurácia bude o 3 dni deaktivovaná.",
    cta: "Aktualizovať platbu",
    help: "Ak máte akékoľvek problémy, vždy sa môžete obrátiť na našu podporu — stačí odpovedať na tento e-mail.",
    closing: "Ďakujeme, že používate IQ Rest.",
    signature: "S pozdravom,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  sl: {
    subject: "Plačilo ni uspelo — posodobi svojo kartico",
    greeting: "Živjo,",
    body: "Nismo mogli obdelati tvojega zadnjega plačila v IQ Rest. Prosimo, posodobi podatke o kartici in ponovno poskusi s plačilom, da bo tvoja restavracija še naprej delovala. Če plačilo ne bo uspešno, bo tvoja restavracija čez 3 dni izklopljena.",
    cta: "Posodobi plačilo",
    help: "Če imaš kakršne koli težave, se lahko vedno obrneš na našo podporo — samo odgovori na to e-pošto.",
    closing: "Hvala, da uporabljaš IQ Rest.",
    signature: "Lep pozdrav,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  sr: {
    subject: "Плаћање није успело — ажурирај своју картицу",
    greeting: "Здраво,",
    body: "Нисмо могли да обрадимо твоје последње плаћање у IQ Rest-у. Молимо те да ажурираш податке о картици и поново покушаш плаћање како би твој ресторан наставио да ради. Ако плаћање не успе, твој ресторан ће бити искључен за 3 дана.",
    cta: "Ажурирај плаћање",
    help: "Ако имаш било какав проблем, увек можеш да се обратиш нашој подршци — само одговори на овај имејл.",
    closing: "Хвала што користиш IQ Rest.",
    signature: "Поздрав,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  sv: {
    subject: "Betalningen misslyckades — uppdatera ditt kort",
    greeting: "Hej,",
    body: "Vi kunde inte behandla din senaste IQ Rest-betalning. Uppdatera dina kortuppgifter och försök med betalningen igen för att hålla din restaurang igång. Om betalningen inte går igenom stängs din restaurang av om 3 dagar.",
    cta: "Uppdatera betalning",
    help: "Om du har några problem kan du alltid kontakta vår support — svara bara på det här mejlet.",
    closing: "Tack för att du använder IQ Rest.",
    signature: "Vänliga hälsningar,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  tr: {
    subject: "Ödeme başarısız oldu — kartınızı güncelleyin",
    greeting: "Merhaba,",
    body: "Son IQ Rest ödemenizi işleme alamadık. Restoranınızın çalışmaya devam etmesi için lütfen kart bilgilerinizi güncelleyin ve ödemeyi tekrar deneyin. Ödeme gerçekleşmezse, restoranınız 3 gün içinde kapatılacaktır.",
    cta: "Ödemeyi güncelle",
    help: "Herhangi bir sorun yaşarsanız her zaman destek ekibimize ulaşabilirsiniz — bu e-postayı yanıtlamanız yeterli.",
    closing: "IQ Rest'i kullandığınız için teşekkürler.",
    signature: "Saygılarımla,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  uk: {
    subject: "Оплата не пройшла — оновіть дані картки",
    greeting: "Вітаю,",
    body: "Нам не вдалося провести ваш останній платіж в IQ Rest. Будь ласка, оновіть дані картки та повторіть платіж, щоб ваш ресторан продовжував працювати. Якщо платіж не пройде, ваш ресторан буде вимкнено через 3 дні.",
    cta: "Оновити оплату",
    help: "Якщо виникнуть будь-які проблеми, ви завжди можете звернутися до нашої підтримки — просто дайте відповідь на цей лист.",
    closing: "Дякуємо, що користуєтеся IQ Rest.",
    signature: "З повагою,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  zh: {
    subject: "支付失败——请更新您的银行卡",
    greeting: "您好，",
    body: "我们无法处理您最近的 IQ Rest 付款。请更新您的银行卡信息并重新尝试付款，以保持您的餐厅正常运营。如果付款未能完成，您的餐厅将在 3 天后被停用。",
    cta: "更新付款",
    help: "如果您遇到任何问题，随时可以联系我们的支持团队——只需回复此邮件即可。",
    closing: "感谢您使用 IQ Rest。",
    signature: "此致，<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
};

const RTL = new Set(["ar", "fa"]);
export function isRtl(locale: string): boolean {
  return RTL.has(locale);
}

export function pickPaymentFailed(locale: string): T {
  return PAYMENT_FAILED[locale] || PAYMENT_FAILED.en;
}
