// Reservation status-change email — sent to the guest when an owner moves a
// reservation to "confirmed" or "cancelled" in the dashboard. Strings cover
// all 35 supported menu locales. Placeholders: {name}, {restaurant}, {date},
// {time}, {guests}, {table}.

interface T {
  subjectConfirmed: string;
  subjectCancelled: string;
  greeting: string;
  bodyConfirmed: string;
  bodyCancelled: string;
  detailsLabel: string;
  dateLabel: string;
  timeLabel: string;
  guestsLabel: string;
  tableLabel: string;
  outroConfirmed: string;
  outroCancelled: string;
  signature: string;
}

const RTL = new Set(["ar", "fa", "he"]);
export function isRtl(locale: string): boolean {
  return RTL.has(locale);
}

export const RESERVATION_STATUS: Record<string, T> = {
  ar: {
    subjectConfirmed: "تم تأكيد حجزك في {restaurant}",
    subjectCancelled: "تم إلغاء حجزك في {restaurant}",
    greeting: "مرحبًا {name}،",
    bodyConfirmed: "تم تأكيد حجزك في {restaurant}.",
    bodyCancelled: "تم إلغاء حجزك في {restaurant}.",
    detailsLabel: "التفاصيل",
    dateLabel: "التاريخ",
    timeLabel: "الوقت",
    guestsLabel: "الضيوف",
    tableLabel: "الطاولة",
    outroConfirmed: "نتطلع إلى استقبالك!",
    outroCancelled: "نأمل أن نستضيفك في وقت آخر.",
    signature: "فريق {restaurant}",
  },
  bg: {
    subjectConfirmed: "Резервацията Ви в {restaurant} е потвърдена",
    subjectCancelled: "Резервацията Ви в {restaurant} е отменена",
    greeting: "Здравейте, {name},",
    bodyConfirmed: "Резервацията Ви в {restaurant} е потвърдена.",
    bodyCancelled: "Резервацията Ви в {restaurant} беше отменена.",
    detailsLabel: "Детайли",
    dateLabel: "Дата",
    timeLabel: "Час",
    guestsLabel: "Гости",
    tableLabel: "Маса",
    outroConfirmed: "Очакваме Ви!",
    outroCancelled: "Надяваме се да Ви посрещнем друг път.",
    signature: "Екипът на {restaurant}",
  },
  ca: {
    subjectConfirmed: "Reserva confirmada a {restaurant}",
    subjectCancelled: "Reserva cancel·lada a {restaurant}",
    greeting: "Hola, {name},",
    bodyConfirmed: "La teva reserva a {restaurant} està confirmada.",
    bodyCancelled: "La teva reserva a {restaurant} ha estat cancel·lada.",
    detailsLabel: "Detalls",
    dateLabel: "Data",
    timeLabel: "Hora",
    guestsLabel: "Comensals",
    tableLabel: "Taula",
    outroConfirmed: "T'esperem!",
    outroCancelled: "Esperem rebre't en una altra ocasió.",
    signature: "L'equip de {restaurant}",
  },
  cs: {
    subjectConfirmed: "Rezervace v restauraci {restaurant} potvrzena",
    subjectCancelled: "Rezervace v restauraci {restaurant} zrušena",
    greeting: "Dobrý den, {name},",
    bodyConfirmed: "Vaše rezervace v restauraci {restaurant} byla potvrzena.",
    bodyCancelled: "Vaše rezervace v restauraci {restaurant} byla zrušena.",
    detailsLabel: "Podrobnosti",
    dateLabel: "Datum",
    timeLabel: "Čas",
    guestsLabel: "Hosté",
    tableLabel: "Stůl",
    outroConfirmed: "Těšíme se na vás!",
    outroCancelled: "Doufáme, že vás přivítáme jindy.",
    signature: "Tým {restaurant}",
  },
  da: {
    subjectConfirmed: "Reservation bekræftet hos {restaurant}",
    subjectCancelled: "Reservation annulleret hos {restaurant}",
    greeting: "Hej {name},",
    bodyConfirmed: "Din reservation hos {restaurant} er bekræftet.",
    bodyCancelled: "Din reservation hos {restaurant} er annulleret.",
    detailsLabel: "Detaljer",
    dateLabel: "Dato",
    timeLabel: "Tid",
    guestsLabel: "Gæster",
    tableLabel: "Bord",
    outroConfirmed: "Vi glæder os til at se dig!",
    outroCancelled: "Vi håber at se dig en anden gang.",
    signature: "{restaurant}-teamet",
  },
  de: {
    subjectConfirmed: "Reservierung bei {restaurant} bestätigt",
    subjectCancelled: "Reservierung bei {restaurant} storniert",
    greeting: "Hallo {name},",
    bodyConfirmed: "Ihre Reservierung bei {restaurant} ist bestätigt.",
    bodyCancelled: "Ihre Reservierung bei {restaurant} wurde storniert.",
    detailsLabel: "Details",
    dateLabel: "Datum",
    timeLabel: "Uhrzeit",
    guestsLabel: "Gäste",
    tableLabel: "Tisch",
    outroConfirmed: "Wir freuen uns auf Sie!",
    outroCancelled: "Wir hoffen, Sie ein anderes Mal begrüßen zu dürfen.",
    signature: "Das {restaurant}-Team",
  },
  el: {
    subjectConfirmed: "Επιβεβαίωση κράτησης στο {restaurant}",
    subjectCancelled: "Ακύρωση κράτησης στο {restaurant}",
    greeting: "Γεια σας, {name},",
    bodyConfirmed: "Η κράτησή σας στο {restaurant} επιβεβαιώθηκε.",
    bodyCancelled: "Η κράτησή σας στο {restaurant} ακυρώθηκε.",
    detailsLabel: "Λεπτομέρειες",
    dateLabel: "Ημερομηνία",
    timeLabel: "Ώρα",
    guestsLabel: "Άτομα",
    tableLabel: "Τραπέζι",
    outroConfirmed: "Σας περιμένουμε!",
    outroCancelled: "Ελπίζουμε να σας υποδεχτούμε άλλη φορά.",
    signature: "Η ομάδα του {restaurant}",
  },
  en: {
    subjectConfirmed: "Reservation confirmed at {restaurant}",
    subjectCancelled: "Reservation cancelled at {restaurant}",
    greeting: "Hi {name},",
    bodyConfirmed: "Your reservation at {restaurant} is confirmed.",
    bodyCancelled: "Your reservation at {restaurant} has been cancelled.",
    detailsLabel: "Details",
    dateLabel: "Date",
    timeLabel: "Time",
    guestsLabel: "Guests",
    tableLabel: "Table",
    outroConfirmed: "We look forward to seeing you!",
    outroCancelled: "We hope to host you another time.",
    signature: "The {restaurant} team",
  },
  es: {
    subjectConfirmed: "Reserva confirmada en {restaurant}",
    subjectCancelled: "Reserva cancelada en {restaurant}",
    greeting: "Hola, {name},",
    bodyConfirmed: "Tu reserva en {restaurant} está confirmada.",
    bodyCancelled: "Tu reserva en {restaurant} ha sido cancelada.",
    detailsLabel: "Detalles",
    dateLabel: "Fecha",
    timeLabel: "Hora",
    guestsLabel: "Comensales",
    tableLabel: "Mesa",
    outroConfirmed: "¡Te esperamos!",
    outroCancelled: "Esperamos recibirte en otra ocasión.",
    signature: "El equipo de {restaurant}",
  },
  et: {
    subjectConfirmed: "Broneering kinnitatud restoranis {restaurant}",
    subjectCancelled: "Broneering tühistatud restoranis {restaurant}",
    greeting: "Tere, {name},",
    bodyConfirmed: "Sinu broneering restoranis {restaurant} on kinnitatud.",
    bodyCancelled: "Sinu broneering restoranis {restaurant} on tühistatud.",
    detailsLabel: "Üksikasjad",
    dateLabel: "Kuupäev",
    timeLabel: "Aeg",
    guestsLabel: "Külalised",
    tableLabel: "Laud",
    outroConfirmed: "Ootame sind!",
    outroCancelled: "Loodame sind teinekord võõrustada.",
    signature: "{restaurant} tiim",
  },
  fa: {
    subjectConfirmed: "رزرو شما در {restaurant} تأیید شد",
    subjectCancelled: "رزرو شما در {restaurant} لغو شد",
    greeting: "سلام {name}،",
    bodyConfirmed: "رزرو شما در {restaurant} تأیید شده است.",
    bodyCancelled: "رزرو شما در {restaurant} لغو شده است.",
    detailsLabel: "جزئیات",
    dateLabel: "تاریخ",
    timeLabel: "ساعت",
    guestsLabel: "مهمانان",
    tableLabel: "میز",
    outroConfirmed: "مشتاق دیدارتان هستیم!",
    outroCancelled: "امیدواریم در فرصتی دیگر میزبان شما باشیم.",
    signature: "تیم {restaurant}",
  },
  fi: {
    subjectConfirmed: "Varaus ravintolaan {restaurant} vahvistettu",
    subjectCancelled: "Varaus ravintolaan {restaurant} peruutettu",
    greeting: "Hei {name},",
    bodyConfirmed: "Varauksesi ravintolaan {restaurant} on vahvistettu.",
    bodyCancelled: "Varauksesi ravintolaan {restaurant} on peruutettu.",
    detailsLabel: "Tiedot",
    dateLabel: "Päivämäärä",
    timeLabel: "Aika",
    guestsLabel: "Henkilömäärä",
    tableLabel: "Pöytä",
    outroConfirmed: "Odotamme käyntiäsi!",
    outroCancelled: "Toivomme näkevämme sinut toiste.",
    signature: "{restaurant}-tiimi",
  },
  fr: {
    subjectConfirmed: "Réservation confirmée chez {restaurant}",
    subjectCancelled: "Réservation annulée chez {restaurant}",
    greeting: "Bonjour {name},",
    bodyConfirmed: "Votre réservation chez {restaurant} est confirmée.",
    bodyCancelled: "Votre réservation chez {restaurant} a été annulée.",
    detailsLabel: "Détails",
    dateLabel: "Date",
    timeLabel: "Heure",
    guestsLabel: "Convives",
    tableLabel: "Table",
    outroConfirmed: "Au plaisir de vous accueillir !",
    outroCancelled: "Nous espérons vous accueillir une prochaine fois.",
    signature: "L'équipe {restaurant}",
  },
  ga: {
    subjectConfirmed: "Áirithint dearbhaithe ag {restaurant}",
    subjectCancelled: "Áirithint curtha ar ceal ag {restaurant}",
    greeting: "Dia duit, {name},",
    bodyConfirmed: "Tá d'áirithint ag {restaurant} dearbhaithe.",
    bodyCancelled: "Tá d'áirithint ag {restaurant} curtha ar ceal.",
    detailsLabel: "Sonraí",
    dateLabel: "Dáta",
    timeLabel: "Am",
    guestsLabel: "Aíonna",
    tableLabel: "Bord",
    outroConfirmed: "Táimid ag tnúth le do theacht!",
    outroCancelled: "Tá súil againn fáilte a chur romhat uair eile.",
    signature: "Foireann {restaurant}",
  },
  hr: {
    subjectConfirmed: "Rezervacija potvrđena u restoranu {restaurant}",
    subjectCancelled: "Rezervacija otkazana u restoranu {restaurant}",
    greeting: "Pozdrav, {name},",
    bodyConfirmed: "Vaša rezervacija u restoranu {restaurant} je potvrđena.",
    bodyCancelled: "Vaša rezervacija u restoranu {restaurant} je otkazana.",
    detailsLabel: "Detalji",
    dateLabel: "Datum",
    timeLabel: "Vrijeme",
    guestsLabel: "Gosti",
    tableLabel: "Stol",
    outroConfirmed: "Veselimo se vašem dolasku!",
    outroCancelled: "Nadamo se vašem posjetu drugom prilikom.",
    signature: "Tim restorana {restaurant}",
  },
  hu: {
    subjectConfirmed: "Foglalás megerősítve a(z) {restaurant} étteremben",
    subjectCancelled: "Foglalás törölve a(z) {restaurant} étteremben",
    greeting: "Szia, {name},",
    bodyConfirmed: "Foglalásodat a(z) {restaurant} étteremben megerősítettük.",
    bodyCancelled: "Foglalásodat a(z) {restaurant} étteremben töröltük.",
    detailsLabel: "Részletek",
    dateLabel: "Dátum",
    timeLabel: "Időpont",
    guestsLabel: "Vendégek",
    tableLabel: "Asztal",
    outroConfirmed: "Várunk szeretettel!",
    outroCancelled: "Reméljük, máskor vendégül láthatunk.",
    signature: "A(z) {restaurant} csapata",
  },
  is: {
    subjectConfirmed: "Bókun staðfest hjá {restaurant}",
    subjectCancelled: "Bókun afpöntuð hjá {restaurant}",
    greeting: "Hæ {name},",
    bodyConfirmed: "Bókun þín hjá {restaurant} er staðfest.",
    bodyCancelled: "Bókun þín hjá {restaurant} hefur verið afpöntuð.",
    detailsLabel: "Upplýsingar",
    dateLabel: "Dagsetning",
    timeLabel: "Tími",
    guestsLabel: "Gestir",
    tableLabel: "Borð",
    outroConfirmed: "Við hlökkum til að sjá þig!",
    outroCancelled: "Við vonumst til að sjá þig síðar.",
    signature: "{restaurant}-teymið",
  },
  it: {
    subjectConfirmed: "Prenotazione confermata da {restaurant}",
    subjectCancelled: "Prenotazione annullata da {restaurant}",
    greeting: "Ciao {name},",
    bodyConfirmed: "La tua prenotazione da {restaurant} è confermata.",
    bodyCancelled: "La tua prenotazione da {restaurant} è stata annullata.",
    detailsLabel: "Dettagli",
    dateLabel: "Data",
    timeLabel: "Ora",
    guestsLabel: "Ospiti",
    tableLabel: "Tavolo",
    outroConfirmed: "Ti aspettiamo!",
    outroCancelled: "Speriamo di accoglierti un'altra volta.",
    signature: "Il team di {restaurant}",
  },
  ja: {
    subjectConfirmed: "{restaurant}のご予約が確定しました",
    subjectCancelled: "{restaurant}のご予約がキャンセルされました",
    greeting: "{name}様",
    bodyConfirmed: "{restaurant}のご予約が確定しました。",
    bodyCancelled: "{restaurant}のご予約はキャンセルされました。",
    detailsLabel: "詳細",
    dateLabel: "日付",
    timeLabel: "時間",
    guestsLabel: "人数",
    tableLabel: "テーブル",
    outroConfirmed: "お会いできるのを楽しみにしております。",
    outroCancelled: "またのお越しを心よりお待ちしております。",
    signature: "{restaurant}スタッフ一同",
  },
  ko: {
    subjectConfirmed: "{restaurant} 예약이 확정되었습니다",
    subjectCancelled: "{restaurant} 예약이 취소되었습니다",
    greeting: "{name}님,",
    bodyConfirmed: "{restaurant}에 하신 예약이 확정되었습니다.",
    bodyCancelled: "{restaurant}에 하신 예약이 취소되었습니다.",
    detailsLabel: "상세 정보",
    dateLabel: "날짜",
    timeLabel: "시간",
    guestsLabel: "인원",
    tableLabel: "테이블",
    outroConfirmed: "방문을 기다리겠습니다!",
    outroCancelled: "다음 기회에 모실 수 있길 바랍니다.",
    signature: "{restaurant} 팀",
  },
  lt: {
    subjectConfirmed: "Rezervacija patvirtinta restorane {restaurant}",
    subjectCancelled: "Rezervacija atšaukta restorane {restaurant}",
    greeting: "Sveiki, {name},",
    bodyConfirmed: "Jūsų rezervacija restorane {restaurant} patvirtinta.",
    bodyCancelled: "Jūsų rezervacija restorane {restaurant} atšaukta.",
    detailsLabel: "Informacija",
    dateLabel: "Data",
    timeLabel: "Laikas",
    guestsLabel: "Svečiai",
    tableLabel: "Staliukas",
    outroConfirmed: "Lauksime jūsų!",
    outroCancelled: "Tikimės pamatyti jus kitą kartą.",
    signature: "{restaurant} komanda",
  },
  lv: {
    subjectConfirmed: "Rezervācija apstiprināta restorānā {restaurant}",
    subjectCancelled: "Rezervācija atcelta restorānā {restaurant}",
    greeting: "Sveiki, {name},",
    bodyConfirmed: "Jūsu rezervācija restorānā {restaurant} ir apstiprināta.",
    bodyCancelled: "Jūsu rezervācija restorānā {restaurant} ir atcelta.",
    detailsLabel: "Detaļas",
    dateLabel: "Datums",
    timeLabel: "Laiks",
    guestsLabel: "Viesi",
    tableLabel: "Galds",
    outroConfirmed: "Gaidīsim jūs!",
    outroCancelled: "Ceram jūs sagaidīt citreiz.",
    signature: "{restaurant} komanda",
  },
  nl: {
    subjectConfirmed: "Reservering bevestigd bij {restaurant}",
    subjectCancelled: "Reservering geannuleerd bij {restaurant}",
    greeting: "Hallo {name},",
    bodyConfirmed: "Je reservering bij {restaurant} is bevestigd.",
    bodyCancelled: "Je reservering bij {restaurant} is geannuleerd.",
    detailsLabel: "Details",
    dateLabel: "Datum",
    timeLabel: "Tijd",
    guestsLabel: "Gasten",
    tableLabel: "Tafel",
    outroConfirmed: "We kijken uit naar je komst!",
    outroCancelled: "We hopen je een andere keer te ontvangen.",
    signature: "Het {restaurant}-team",
  },
  no: {
    subjectConfirmed: "Reservasjon bekreftet hos {restaurant}",
    subjectCancelled: "Reservasjon avlyst hos {restaurant}",
    greeting: "Hei {name},",
    bodyConfirmed: "Reservasjonen din hos {restaurant} er bekreftet.",
    bodyCancelled: "Reservasjonen din hos {restaurant} er avlyst.",
    detailsLabel: "Detaljer",
    dateLabel: "Dato",
    timeLabel: "Tid",
    guestsLabel: "Gjester",
    tableLabel: "Bord",
    outroConfirmed: "Vi gleder oss til å se deg!",
    outroCancelled: "Vi håper å se deg en annen gang.",
    signature: "{restaurant}-teamet",
  },
  pl: {
    subjectConfirmed: "Rezerwacja potwierdzona w restauracji {restaurant}",
    subjectCancelled: "Rezerwacja anulowana w restauracji {restaurant}",
    greeting: "Cześć, {name},",
    bodyConfirmed: "Twoja rezerwacja w restauracji {restaurant} została potwierdzona.",
    bodyCancelled: "Twoja rezerwacja w restauracji {restaurant} została anulowana.",
    detailsLabel: "Szczegóły",
    dateLabel: "Data",
    timeLabel: "Godzina",
    guestsLabel: "Goście",
    tableLabel: "Stolik",
    outroConfirmed: "Czekamy na Ciebie!",
    outroCancelled: "Mamy nadzieję gościć Cię innym razem.",
    signature: "Zespół {restaurant}",
  },
  pt: {
    subjectConfirmed: "Reserva confirmada em {restaurant}",
    subjectCancelled: "Reserva cancelada em {restaurant}",
    greeting: "Olá {name},",
    bodyConfirmed: "A sua reserva em {restaurant} está confirmada.",
    bodyCancelled: "A sua reserva em {restaurant} foi cancelada.",
    detailsLabel: "Detalhes",
    dateLabel: "Data",
    timeLabel: "Hora",
    guestsLabel: "Pessoas",
    tableLabel: "Mesa",
    outroConfirmed: "Esperamos vê-lo em breve!",
    outroCancelled: "Esperamos recebê-lo em outra ocasião.",
    signature: "Equipa {restaurant}",
  },
  ro: {
    subjectConfirmed: "Rezervare confirmată la {restaurant}",
    subjectCancelled: "Rezervare anulată la {restaurant}",
    greeting: "Bună, {name},",
    bodyConfirmed: "Rezervarea ta la {restaurant} este confirmată.",
    bodyCancelled: "Rezervarea ta la {restaurant} a fost anulată.",
    detailsLabel: "Detalii",
    dateLabel: "Data",
    timeLabel: "Ora",
    guestsLabel: "Invitați",
    tableLabel: "Masa",
    outroConfirmed: "Te așteptăm!",
    outroCancelled: "Sperăm să te primim altă dată.",
    signature: "Echipa {restaurant}",
  },
  ru: {
    subjectConfirmed: "Бронирование в ресторане {restaurant} подтверждено",
    subjectCancelled: "Бронирование в ресторане {restaurant} отменено",
    greeting: "Здравствуйте, {name}!",
    bodyConfirmed: "Ваше бронирование в ресторане {restaurant} подтверждено.",
    bodyCancelled: "Ваше бронирование в ресторане {restaurant} отменено.",
    detailsLabel: "Детали",
    dateLabel: "Дата",
    timeLabel: "Время",
    guestsLabel: "Гостей",
    tableLabel: "Стол",
    outroConfirmed: "Ждём вас в гости!",
    outroCancelled: "Надеемся принять вас в другой раз.",
    signature: "Команда {restaurant}",
  },
  sk: {
    subjectConfirmed: "Rezervácia potvrdená v reštaurácii {restaurant}",
    subjectCancelled: "Rezervácia zrušená v reštaurácii {restaurant}",
    greeting: "Dobrý deň, {name},",
    bodyConfirmed: "Vaša rezervácia v reštaurácii {restaurant} je potvrdená.",
    bodyCancelled: "Vaša rezervácia v reštaurácii {restaurant} bola zrušená.",
    detailsLabel: "Podrobnosti",
    dateLabel: "Dátum",
    timeLabel: "Čas",
    guestsLabel: "Hostia",
    tableLabel: "Stôl",
    outroConfirmed: "Tešíme sa na vás!",
    outroCancelled: "Dúfame, že vás privítame nabudúce.",
    signature: "Tím {restaurant}",
  },
  sl: {
    subjectConfirmed: "Rezervacija potrjena v restavraciji {restaurant}",
    subjectCancelled: "Rezervacija preklicana v restavraciji {restaurant}",
    greeting: "Pozdravljeni, {name},",
    bodyConfirmed: "Vaša rezervacija v restavraciji {restaurant} je potrjena.",
    bodyCancelled: "Vaša rezervacija v restavraciji {restaurant} je preklicana.",
    detailsLabel: "Podrobnosti",
    dateLabel: "Datum",
    timeLabel: "Čas",
    guestsLabel: "Gostje",
    tableLabel: "Miza",
    outroConfirmed: "Veselimo se vašega obiska!",
    outroCancelled: "Upamo, da vas bomo videli drugič.",
    signature: "Ekipa {restaurant}",
  },
  sr: {
    subjectConfirmed: "Rezervacija potvrđena u restoranu {restaurant}",
    subjectCancelled: "Rezervacija otkazana u restoranu {restaurant}",
    greeting: "Zdravo, {name},",
    bodyConfirmed: "Vaša rezervacija u restoranu {restaurant} je potvrđena.",
    bodyCancelled: "Vaša rezervacija u restoranu {restaurant} je otkazana.",
    detailsLabel: "Detalji",
    dateLabel: "Datum",
    timeLabel: "Vreme",
    guestsLabel: "Gosti",
    tableLabel: "Sto",
    outroConfirmed: "Radujemo se vašem dolasku!",
    outroCancelled: "Nadamo se da ćemo vas ugostiti drugi put.",
    signature: "Tim restorana {restaurant}",
  },
  sv: {
    subjectConfirmed: "Reservation bekräftad hos {restaurant}",
    subjectCancelled: "Reservation avbokad hos {restaurant}",
    greeting: "Hej {name},",
    bodyConfirmed: "Din reservation hos {restaurant} är bekräftad.",
    bodyCancelled: "Din reservation hos {restaurant} är avbokad.",
    detailsLabel: "Detaljer",
    dateLabel: "Datum",
    timeLabel: "Tid",
    guestsLabel: "Gäster",
    tableLabel: "Bord",
    outroConfirmed: "Vi ser fram emot att se dig!",
    outroCancelled: "Vi hoppas få välkomna dig en annan gång.",
    signature: "{restaurant}-teamet",
  },
  tr: {
    subjectConfirmed: "{restaurant} rezervasyonunuz onaylandı",
    subjectCancelled: "{restaurant} rezervasyonunuz iptal edildi",
    greeting: "Merhaba {name},",
    bodyConfirmed: "{restaurant} rezervasyonunuz onaylandı.",
    bodyCancelled: "{restaurant} rezervasyonunuz iptal edildi.",
    detailsLabel: "Detaylar",
    dateLabel: "Tarih",
    timeLabel: "Saat",
    guestsLabel: "Misafirler",
    tableLabel: "Masa",
    outroConfirmed: "Sizi görmek için sabırsızlanıyoruz!",
    outroCancelled: "Sizi başka bir zaman ağırlamayı umuyoruz.",
    signature: "{restaurant} ekibi",
  },
  uk: {
    subjectConfirmed: "Бронювання в ресторані {restaurant} підтверджено",
    subjectCancelled: "Бронювання в ресторані {restaurant} скасовано",
    greeting: "Вітаємо, {name}!",
    bodyConfirmed: "Ваше бронювання в ресторані {restaurant} підтверджено.",
    bodyCancelled: "Ваше бронювання в ресторані {restaurant} скасовано.",
    detailsLabel: "Деталі",
    dateLabel: "Дата",
    timeLabel: "Час",
    guestsLabel: "Гостей",
    tableLabel: "Стіл",
    outroConfirmed: "Чекаємо на вас!",
    outroCancelled: "Сподіваємося прийняти вас іншим разом.",
    signature: "Команда {restaurant}",
  },
  zh: {
    subjectConfirmed: "{restaurant}的预订已确认",
    subjectCancelled: "{restaurant}的预订已取消",
    greeting: "{name}您好，",
    bodyConfirmed: "您在{restaurant}的预订已确认。",
    bodyCancelled: "您在{restaurant}的预订已取消。",
    detailsLabel: "详情",
    dateLabel: "日期",
    timeLabel: "时间",
    guestsLabel: "人数",
    tableLabel: "餐桌",
    outroConfirmed: "期待您的光临！",
    outroCancelled: "希望下次能再接待您。",
    signature: "{restaurant} 团队",
  },
};

export function pickReservationStatus(locale: string): T {
  return RESERVATION_STATUS[locale] || RESERVATION_STATUS.en;
}
